name: 🔒 Security Scan

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git diff
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install rnsec
      run: npm install -g rnsec
    
    - name: Run security scan on changed files
      run: |
        # Generate markdown report for PR comment
        rnsec scan --changed-files ${{ github.base_ref || 'main' }} --md security-report.md --silent
        
        # Also generate HTML and JSON reports for detailed analysis and comparison
        rnsec scan --changed-files ${{ github.base_ref || 'main' }} --html security-report.html --output rnsec-report.json --silent
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-report.md
          security-report.html
        retention-days: 30
    
    - name: Comment PR with security results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          try {
            const markdownReport = fs.readFileSync('security-report.md', 'utf8');
            const commentIdentifier = '<!-- rnsec-security-report -->';
            
            // Find existing rnsec comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const existingComment = comments.find(comment => 
              comment.body?.includes(commentIdentifier)
            );
            
            // Extract previous scan results for comparison
            let previousFindings = [];
            if (existingComment) {
              // Parse JSON data from previous comment if available
              const jsonMatch = existingComment.body.match(/<!-- scan-data: (.*?) -->/);
              if (jsonMatch) {
                try {
                  previousFindings = JSON.parse(Buffer.from(jsonMatch[1], 'base64').toString());
                } catch (e) {
                  console.log('Could not parse previous scan data');
                }
              }
            }
            
            // Add current scan data as hidden JSON for next comparison
            let currentFindings = [];
            try {
              const jsonReport = JSON.parse(fs.readFileSync('rnsec-report.json', 'utf8'));
              currentFindings = jsonReport.findings || [];
            } catch (e) {
              console.log('Could not read JSON report for comparison');
            }
            
            // Embed scan data in comment for future comparisons
            const scanDataComment = currentFindings.length > 0 
              ? `\n<!-- scan-data: ${Buffer.from(JSON.stringify(currentFindings)).toString('base64')} -->`
              : '';
            
            const finalReport = markdownReport + scanDataComment;
            
            if (existingComment) {
              // Update existing comment with comparison
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: finalReport
              });
              console.log('Updated existing security report comment with comparison data');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: finalReport
              });
              console.log('Created new security report comment');
            }
          } catch (error) {
            console.log('Error posting security report:', error.message);
          }
    
    - name: Full security scan (optional)
      if: github.event_name == 'push'
      run: |
        # Run full scan on pushes to main branch
        rnsec scan --md full-security-report.md --html full-security-report.html --json full-security-report.json
      continue-on-error: true
    
    - name: Upload full scan reports
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: full-security-reports
        path: |
          full-security-report.md
          full-security-report.html
          full-security-report.json
        retention-days: 30
