name: 🔒 Security Scan

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git diff
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install rnsec
      run: npm install -g rnsec
    
    - name: Run security scan on changed files
      run: |
        # Generate markdown report for PR comment
        rnsec scan --changed-files ${{ github.base_ref || 'main' }} --md security-report.md --silent
        
        # Also generate HTML report for detailed analysis
        rnsec scan --changed-files ${{ github.base_ref || 'main' }} --html security-report.html --silent
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-report.md
          security-report.html
        retention-days: 30
    
    - name: Comment PR with security results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          try {
            const markdownReport = fs.readFileSync('security-report.md', 'utf8');
            const commentIdentifier = '<!-- rnsec-security-report -->';
            
            // Find existing rnsec comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const existingComment = comments.find(comment => 
              comment.body?.includes(commentIdentifier)
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: markdownReport
              });
              console.log('Updated existing security report comment');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: markdownReport
              });
              console.log('Created new security report comment');
            }
          } catch (error) {
            console.log('Error posting security report:', error.message);
          }
    
    - name: Full security scan (optional)
      if: github.event_name == 'push'
      run: |
        # Run full scan on pushes to main branch
        rnsec scan --md full-security-report.md --html full-security-report.html --json full-security-report.json
      continue-on-error: true
    
    - name: Upload full scan reports
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: full-security-reports
        path: |
          full-security-report.md
          full-security-report.html
          full-security-report.json
        retention-days: 30
