import type { Finding, ScanResult } from '../types/findings.js';

export class MarkdownReporter {
  /**
   * Generate markdown report for GitHub PR comments
   */
  generateReport(result: ScanResult): string {
    const { findings, scannedFiles, duration, timestamp } = result;
    
    if (findings.length === 0) {
      return this.generateSuccessReport(result);
    }
    
    return this.generateVulnerabilityReport(result);
  }

  private generateSuccessReport(result: ScanResult): string {
    const { scannedFiles, duration } = result;
    
    return `## 🔒 Security Scan Results

✅ **No security vulnerabilities detected**

Your React Native app passed all security checks!

### 📊 Scan Summary
| Metric | Value |
|--------|-------|
| 🔴 High Severity | 0 |
| 🟡 Medium Severity | 0 |
| 🔵 Low Severity | 0 |
| 📁 Files Scanned | ${scannedFiles || 'N/A'} |
| ⚡ Duration | ${(duration / 1000).toFixed(2)}s |
| 🕐 Completed | ${result.timestamp.toLocaleString()} |

### 🎉 Risk Level: SECURE
Great job! No security vulnerabilities detected.

---

*Generated by [rnsec](https://github.com/adnxy/rnsec) - React Native Security Scanner*`;
  }

  private generateVulnerabilityReport(result: ScanResult): string {
    const { findings, scannedFiles, duration, timestamp } = result;
    
    const high = findings.filter(f => f.severity === 'HIGH').length;
    const medium = findings.filter(f => f.severity === 'MEDIUM').length;
    const low = findings.filter(f => f.severity === 'LOW').length;
    
    const riskLevel = high >= 3 ? '🚨 CRITICAL' 
      : high >= 1 ? '⚠️ HIGH' 
      : medium >= 3 ? '⚠️ MODERATE'
      : medium >= 1 ? 'ℹ️ LOW'
      : 'ℹ️ MINOR';

    let markdown = `## 🔒 Security Scan Results

${riskLevel} **${findings.length} security ${findings.length === 1 ? 'issue' : 'issues'} found**

### 📊 Issue Summary
| Severity | Count | Status |
|----------|-------|--------|
| 🔴 High | ${high} | ${high > 0 ? '❌ Needs attention' : '✅ None'} |
| 🟡 Medium | ${medium} | ${medium > 0 ? '⚠️ Review recommended' : '✅ None'} |
| 🔵 Low | ${low} | ${low > 0 ? 'ℹ️ Address when possible' : '✅ None'} |

### 📈 Scan Performance
| Metric | Value |
|--------|-------|
| 📁 Files Scanned | ${scannedFiles || 'N/A'} |
| ⚡ Duration | ${(duration / 1000).toFixed(2)}s |
| 🕐 Completed | ${result.timestamp.toLocaleString()} |

`;

    // Group findings by severity
    const grouped = this.groupBySeverity(findings);
    
    if (grouped.HIGH.length > 0) {
      markdown += this.generateSeveritySection('🔴 High Severity', grouped.HIGH);
    }
    
    if (grouped.MEDIUM.length > 0) {
      markdown += this.generateSeveritySection('🟡 Medium Severity', grouped.MEDIUM);
    }
    
    if (grouped.LOW.length > 0) {
      markdown += this.generateSeveritySection('🔵 Low Severity', grouped.LOW);
    }

    markdown += `---

### 🎯 Risk Assessment
${this.generateRiskAssessment(high, medium, low)}

---

*Generated by [rnsec](https://github.com/adnxy/rnsec) - React Native Security Scanner*`;

    return markdown;
  }

  private generateSeveritySection(title: string, findings: Finding[]): string {
    let section = `\n### ${title}\n\n`;
    
    findings.forEach((finding, index) => {
      const icon = finding.severity === 'HIGH' ? '🔴' : 
                   finding.severity === 'MEDIUM' ? '🟡' : '🔵';
      
      const location = finding.filePath ? `\`${this.formatFilePath(finding.filePath)}${finding.line ? `:${finding.line}` : ''}\`` : '';
      const debugBadge = finding.isDebugContext ? ' 🐛 [DEBUG]' : '';
      
      section += `${index + 1}. **${icon} ${finding.description || finding.ruleId}**${debugBadge}\n`;
      if (location) {
        section += `   📍 ${location}\n`;
      }
      if (finding.suggestion) {
        section += `   💡 **Suggestion:** ${finding.suggestion}\n`;
      }
      section += '\n';
    });
    
    return section;
  }

  private generateRiskAssessment(high: number, medium: number, low: number): string {
    if (high >= 3) {
      return '🚨 **CRITICAL RISK** - Multiple high-severity vulnerabilities detected. Immediate action required before merging.';
    } else if (high >= 1) {
      return '⚠️ **HIGH RISK** - High-severity vulnerabilities detected. Address before merging if possible.';
    } else if (medium >= 3) {
      return '⚠️ **MODERATE RISK** - Multiple medium-severity issues. Review and address before merging.';
    } else if (medium >= 1) {
      return 'ℹ️ **LOW RISK** - Some medium-severity issues. Address as part of this PR or follow-up.';
    } else if (low >= 1) {
      return 'ℹ️ **MINOR RISK** - Low-severity issues detected. Can be addressed in future iterations.';
    }
    return '✅ **SECURE** - No significant security issues detected.';
  }

  private groupBySeverity(findings: Finding[]): Record<string, Finding[]> {
    return findings.reduce(
      (acc, finding) => {
        acc[finding.severity].push(finding);
        return acc;
      },
      {
        HIGH: [] as Finding[],
        MEDIUM: [] as Finding[],
        LOW: [] as Finding[],
      }
    );
  }

  private formatFilePath(filePath: string): string {
    const parts = filePath.split('/');
    if (parts.length > 3) {
      return '.../' + parts.slice(-3).join('/');
    }
    return filePath;
  }
}
